# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "HoonC-corgi's Blog"
description: > # this means to ignore newlines until "email:"
   A Jekyll theme - Medium inspired

email: tgh7544@naver.com
#blog logo
logo: "/assets/images/author.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/blog_cover.jpg"

name: 'HoonC-corgi'
author: 'HoonC-corgi'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "HoonC-corgi.github.io" # the base hostname & protocol for your site
baseurl: ""

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	instagram
    url:	https://instagram/_ftxm_sx.02/
    desc: Follow/DM me on IG
    share_url:
    share_title:
    share_link:

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/HoonC-corgi
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
